export const AUDIT_ACTIONS = {
  ATTACHMENT_UPLOADED: 'ATTACHMENT_UPLOADED',
  ATTACHMENT_DELETED: 'ATTACHMENT_DELETED',

  REPORT_CSV_EXPORTED: 'REPORT_CSV_EXPORTED',
  REPORT_XLSX_EXPORTED: 'REPORT_XLSX_EXPORTED',
  REPORT_PDF_EXPORTED: 'REPORT_PDF_EXPORTED',

  EQUIPMENT_CREATED: 'EQUIPMENT_CREATED',
  EQUIPMENT_UPDATED: 'EQUIPMENT_UPDATED',
  EQUIPMENT_STATUS_CHANGED: 'EQUIPMENT_STATUS_CHANGED',
  EQUIPMENT_RETIRED: 'EQUIPMENT_RETIRED',

  MAINTENANCE_ORDER_CREATED: 'MAINTENANCE_ORDER_CREATED',
  MAINTENANCE_ORDER_STARTED: 'MAINTENANCE_ORDER_STARTED',
  MAINTENANCE_ORDER_COMPLETED: 'MAINTENANCE_ORDER_COMPLETED',
  MAINTENANCE_ORDER_CANCELLED: 'MAINTENANCE_ORDER_CANCELLED',
} as const;

export const AUDIT_ENTITIES = {
  ATTACHMENT: 'Attachment',
  MAINTENANCE_ORDER: 'MaintenanceOrder',
  EQUIPMENT: 'Equipment',
  REPORT: 'Report',
} as const;
